package com.example.barrelracing;

import java.util.Map;
import java.util.TreeMap;

import com.example.fileIO.FileOperations;


import android.R.color;
import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;

import android.view.Menu;
import android.view.MenuItem;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
/*
 * Code Written By  : Rakesh Manoharan & Pavan Trinath
 * Net ID 			: rxm143130 & BXV131230
 * Course 			: CS6301
 * Class Name		: HighScoreList.java
 * Date				: 12-02-2014
 * Description 		:
 * 		 HighScoreList class is used to display the top ten riders name and their recorder time.
 */

public class HighScoreList extends Activity {
	private TextView name;
	 LinearLayout layout;
	protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.high_scores);
        
        layout=(LinearLayout)findViewById(R.id.listscoreslayout);


        
        FileOperations fileWrite=new FileOperations();
		TreeMap<Long,String> orderedData=fileWrite.read();


		
		
		int i=1;
		// Below for loop is used to traverse through all the top 10 records stored on Tree Map, which is a sorted
		// collection on java. so we just iterate through the 1st 10 key value pair on the tree map.
		for(Map.Entry<Long, String> Iterator:orderedData.entrySet())
        {
        	if(Iterator.getKey()!=null&&i<=10)
        	{
        		LinearLayout innerlayout=new LinearLayout(this);
        		innerlayout.setOrientation(0);
        				
        		name=new TextView(this);
        		name.setBackgroundColor(color.holo_blue_light);
        		name.setTextSize(25);
        		name.setId(i);
        		name.setBottom(600);
        		name.setPadding(0, 8, 0, 0);
        		
        		long score=Iterator.getKey();
        		long diffMilliSecs=(score%1000)/10;
        		long diffSeconds = score / 1000 % 60;
        		long diffMinutes = score / (60 * 1000) % 60;
        		String milliSec=Long.toString(diffMilliSecs);
        		String diffSec=Long.toString(diffSeconds);
        		String min=Long.toString(diffMinutes);
        		if(milliSec.length()<2)
        		{
        			milliSec="0".concat(milliSec);
        		}
        		if(diffSec.length()<2)
        		{
        			diffSec="0".concat(diffSec);
        		}
        		if(min.length()<2)
        		{
        			min="0".concat(min);
        		}
        		
        		
        		String Timer="   ".concat(min).concat(" : ").concat(diffSec).concat(" : ").concat(milliSec).concat("         ");

        		name.setText(Timer);
        		
        		
        		TextView pNo=new TextView(this);
        		pNo.setText(Iterator.getValue());
        		pNo.setTextSize(25);
        		pNo.setPadding(0, 0, 0, 30);
        		//pNo.setTextColor(getResources().getColor(R.color.phonenumbercolor));
        		     	
        		innerlayout.addView(name);
        		innerlayout.addView(pNo);   
        		layout.addView(innerlayout);
        		
        	}
        	i++;
        }
		
	}
	
	   @Override
	    public boolean onCreateOptionsMenu(Menu menu) {
	        // Inflate the menu; this adds items to the action bar if it is present.
	        getMenuInflater().inflate(R.menu.back, menu);
	      
	        return true;
	    }
	    // onOptionsItemSelected is used to handle the event generated by clicking on the controls specified on the action bar.
	    @Override
	    public boolean onOptionsItemSelected(MenuItem item) {
	        // Handle action bar item clicks here. The action bar will
	        // automatically handle clicks on the Home/Up button, so long
	        // as you specify a parent activity in AndroidManifest.xml.
	        int id = item.getItemId();
	        if (id == R.id.homescreen) {
	        	Intent i=new Intent(this,MainActivity.class);
	        	i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK|Intent.FLAG_ACTIVITY_NEW_TASK);
	        	startActivity(i);
	            return true;
	        }
	        return super.onOptionsItemSelected(item);
	    }


}
